In [5]:
'''
infeasible?!

bow_s:
[1. 0. 0. 0.]

bow_t:
[0. 1. 1. 1.]

D:
[[1.         0.5854713  0.8332059  0.80485016]
 [0.5854713  1.         1.         1.        ]
 [0.8332059  1.         1.         1.        ]
 [0.80485016 1.         1.         1.        ]]

'''



w1 = np.array([1., 0., 0., 0.])
w2 = np.array([0., 1., 1., 1.])
D = parse_matrix('''
[[1.         0.5854713  0.8332059  0.80485016]
 [0.5854713  1.         1.         1.        ]
 [0.8332059  1.         1.         1.        ]
 [0.80485016 1.         1.         1.        ]]
''')

from pyemd import emd_with_flow
emd_with_flow(w1, w2, D)

(2.585470414529,
 [[0.0, 0.9999990000000001, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0]])

In [6]:
import ot
ot.emd2(w1, w2, D)

/opt/miniconda3/envs/vectorian2021/lib/python3.8/site-packages/ot/lp/__init__.py:421: UserWarning: Problem infeasible. Check that a and b are in the simplex
  check_result(result_code)


0.0

In [2]:
import re
import json
import numpy as np

def parse_matrix(s):
    s = re.sub('\s+', ',', s.strip())
    s = s.replace(',]', ']')
    s = s.replace('.,', ',')
    s = s.replace('.]', ']')
    return np.array(json.loads(s))

D = parse_matrix('''
[[1.         0.5854713  0.8332059  0.80485016]
 [0.5854713  1.         1.         1.        ]
 [0.8332059  1.         1.         1.        ]
 [0.80485016 1.         1.         1.        ]]
''')

D

array([[1.        , 0.5854713 , 0.8332059 , 0.80485016],
       [0.5854713 , 1.        , 1.        , 1.        ],
       [0.8332059 , 1.        , 1.        , 1.        ],
       [0.80485016, 1.        , 1.        , 1.        ]])

In [12]:
import numpy as np

w1 = np.array([2, 0], dtype=np.float64)
w2 = np.array([0, 1], dtype=np.float64)
d = 0.25
D = np.array([
    [0, d],
    [d, 0]
], dtype=np.float64)

from pyemd import emd_with_flow
emd_with_flow(w1, w2, D)

(0.5, [[0.0, 1.0], [0.0, 0.0]])