In [1]:
import numpy as np

x = np.array([-0.0072517,-0.0193276,-0.0149888,-0.0527077,-0.0219264,0.0146801,0.0113693,0.036387,-0.0160948,0.0142471,-0.0308729,-0.0228216,0.0197928,-0.00544991,0.0118018,0.0512357,-0.0181088,-0.00772532,-0.0364812,0.00189513,-0.00191947,0.00665262,-0.021374,0.010104,-0.00857085,-0.0333865,0.00449376,-0.0110102,-0.0150824,0.0989093,0.000362827,0.00749817,-0.00543,-0.0050601,-0.0136851,-0.00661086,-0.0273833,-0.0967763,0.000339407,0.00717893,-0.0247099,-0.0332084,0.0107581,-0.0328398,-0.0167047,-0.0202006,-0.0266565,0.0142229,-0.0570797,0.00131633,-0.00857016,-0.00405874,0.00971009,0.00444737,-0.022115,-0.0193889,0.0116127,0.0346967,0.036448,0.016773,0.024334,0.00390436,-0.00997996,0.018918,0.0134042,0.00970138,-0.0273965,-0.00430797,0.00610301,0.0187134,0.0446877,-0.0123575,-0.0469951,0.0219964,-0.0100873,0.00175133,-0.00556353,-0.0196795,0.000726143,0.000684535,0.00455683,0.0138868,-0.0165347,0.0350061,-0.0165814,0.012352,-0.0224697,0.0163484,-0.00964853,-0.0063181,-0.0359369,0.000327202,0.0926582,-0.0183958,0.0270203,-0.0220275,0.0157127,-0.0165035,0.0309955,0.0177697,0.00268224,-0.00929149,0.0238312,0.00640837,0.0356675,-0.0109,-0.00192168,0.0132283,0.0220428,0.0154038,-0.0035703,0.0253997,-0.004891,0.0150905,0.0301723,0.0473669,-0.0152338,0.00223085,-0.0092939,-0.00422206,-0.00423545,-0.026939,0.00875872,-0.00806301,-0.0222056,0.0121803,-0.0174519,-0.00974089,-0.00861803,-0.00923141,0.0143504,-0.0061177,0.0247009,-0.0292472,-0.0194458,-0.0081212,-0.0356304,-0.035834,-0.0177393,-0.0217801,-0.0388887,-0.0076277,-0.028748,-0.00297334,-0.0228548,0.00747635,-0.108022,-0.00988702,0.00281152,-0.00643003,-0.0410864,0.00178827,0.0370066,-0.00175653,0.000440586,0.00861645,0.0402597,0.0132069,-0.00701482,-0.0289846,0.0160618,0.0133537,-0.000433748,-0.0369513,0.0173566,0.00261166,0.0263175,-0.00996239,0.0100943,-0.00212303,-0.00939696,-0.0146719,-0.0256213,0.0189317,0.0258114,0.00820165,0.00645122,-0.0100276,-0.0129185,-0.0256343,-0.0218257,-0.0250985,0.0149111,0.0334004,0.0252494,0.0322499,0.00848199,-0.00280296,-0.0127327,0.0225111,-0.00635339,-0.00933378,-0.00986209,-0.0427601,0.00252624,0.00573822,0.0151507,-0.00231423,0.0214282,-0.065586,0.0612042,0.0652295,0.0219155,0.0150884,0.0457455,0.00819505,0.041896,0.00247253,-0.0284248,-0.00364177,-0.0179564,0.0130073,-0.0188199,-0.0170997,0.00178675,-0.00412696,-0.0218299,0.0164586,0.00528486,-0.00126934,-0.0357945,-0.00869646,-0.0399828,0.00755631,-0.0277383,-0.00501714,0.0110878,-0.00554293,0.044786,0.000957434,-0.0147502,-0.0130192,0.00436083,0.0124739,0.0873499,0.0110978,0.0104985,-0.0263252,-0.0154089,0.00746308,0.0112049,0.00747513,0.0135642,0.015247,0.192655,0.0176787,0.0192375,0.00181098,0.000993927,0.00293009,-0.0747322,0.0148335,-0.0127952,0.0310046,0.0216169,0.0145223,0.0368933,-0.00367253,-0.00331374,-0.0267328,-0.00957018,-0.065498,0.115699,0.0106783,0.0271993,-0.0142774,0.0115499,-0.0180051,0.00227382,-0.0335592,0.0368739,-0.0142405,0.0503106,0.0230492,-0.00210775,0.00668504,-0.0130521,-0.0275724,0.0303647,-0.0171128,0.00479436,0.00703794,-0.0263987,-0.0298404,-0.00581748,-0.00936057,0.0059473,0.0230163,0.00477584,-0.00416509,-0.00945044,-0.0250511,0.013062,0.0131064,-0.00572554,-0.0219203,0.0173558,0.04871,-0.0134156,-0.0184355])

In [3]:
x / np.linalg.norm(x)

array([-0.0148753 , -0.0396464 , -0.03074629, -0.10811847, -0.04497728,
        0.03011306,  0.02332167,  0.07464008, -0.03301501,  0.02922485,
       -0.06332909, -0.04681359,  0.04060066, -0.01117931,  0.02420885,
        0.10509898, -0.0371463 , -0.01584683, -0.07483331,  0.00388745,
       -0.00393738,  0.01364641, -0.04384415,  0.02072618, -0.01758125,
       -0.0684852 ,  0.00921798, -0.02258505, -0.03093829,  0.20289108,
        0.00074426,  0.01538088, -0.01113847, -0.0103797 , -0.02807203,
       -0.01356075, -0.05617093, -0.1985157 ,  0.00069622,  0.01472603,
       -0.05068703, -0.06811987,  0.02206792, -0.06736376, -0.03426609,
       -0.04143717, -0.05468006,  0.02917521, -0.11708669,  0.00270017,
       -0.01757983, -0.00832563,  0.01991815,  0.00912282, -0.04536415,
       -0.03977214,  0.02382095,  0.07117279,  0.07476521,  0.03440619,
        0.04991595,  0.00800895, -0.02047173,  0.03880619,  0.02749582,
        0.01990029, -0.05619801, -0.00883687,  0.01251901,  0.03

In [12]:
import numpy as np
M = np.array([
    [1, 3],
    [0, 7]
])
M

array([[1, 3],
       [0, 7]])

In [13]:
np.argmax(M, axis=1)

array([1, 1])